### ISSUE TITLE
UUID_NATIVE does not seem to work with Postgres

### ISSUE THREAD

**Issue by akaoj** [j256/ormlite-core#89] opened 2016-08-27 06:28 UTC
Hello,
After I saw the support for UUID native fields, I switched to the 5.0 release. But it seems either it doesn't work or I'm missing something.
I have a pojo class with a java.util.UUID ID field and the annotation

`@DatabaseField( generatedId=true, dataType=DataType.UUID_NATIVE )`

my database has the field

`"id" uuid not null primary key default uuid_generate_v4()`

but when I try to save an object with

`dao.create( myObj )`

then I have a PSQLException `column "id" is of type uuid but expression is of type character varying`.

If I add `readOnly = true` to the `@DatabaseField`, then the insert works, but the ID returned by my object after the `.create()` is not the ID saved in the database.

Am I doing something bad? Is it possible to handle UUID auto-generated ID values on the database ?

**Comment by akaoj** [comment] 2016-09-05 18:52
Is it possible to actually use the Postgres UUID type with OrmLite or not at all? If not, what is the purpose of

`dataType=DataType.UUID_NATIVE`

?

**Comment by akaoj** [comment] 2016-10-08 07:16
Hi @j256, could you please tell me the purpose of the UUID type if we can't set UUID native columns?

Thanks!

**Comment by j256** [comment] 2016-10-09 17:32
This a snarky comment @akaoj?  Obviously there is a bug somewhere.

**Comment by akaoj** [comment] 2016-10-10 12:31
Hello, absolutely not @j256, but given that I had no answer and nobody else seemed to hit the same issue, I started to think that **I** was the one having an issue with this framework :-)

I tried to check to code to find where the issue could be, but I had no success... I ended up switching to "serial"; but I would be happy to be able to use the native UUID type on Pg.

**Comment by j256** [comment] 2016-10-10 13:31
Thanks for the response.  I think I'm doing all the right things in terms of JDBC but maybe not.  I'll have to do some debugging.

**Comment by Bo98** [comment] 2016-11-20 00:08
FWIW, I'm getting the exact same issue.

**Comment by Bo98** [comment] 2016-11-20 00:16
I fixed my issue by using `persisterClass = NativeUuidType.class`.

The issue is possibly [this line](https://github.com/j256/ormlite-core/blob/c766eebd3b54d23945e09f73f975c3b79077548c/src/main/java/com/j256/ormlite/field/DataType.java#L201) being `UuidType` rather than `NativeUuidType`.

**Comment by j256** [comment] 2016-11-20 17:28
Holy crap.  Yep.  That's a complete fail.  I'll fix that and hopefully push a release sooner.

**Comment by j256** [comment] 2016-11-20 17:33
See: https://github.com/j256/ormlite-core/commit/5896fc37759e0885a673b7e784201b2d9991863b

**Comment by akaoj** [comment] 2017-08-27 14:50
Hi @j256! I'm sorry to kind of "reopen" this issue, but the fix you committed never had the chance to get in a release, so people can't really use it... Could you release the version 5.1 of ORMLite?
Thanks!

**Comment by j256** [comment] 2018-12-01 01:47
Released in February 2018.  Sorry for the delay.

**Closed** 2018-12-01 01:47 UTC
