### ISSUE TITLE
bug ? Postgresql Table exist?

### ISSUE THREAD

**Issue by JavLock** [j256/ormlite-core#218] opened 2021-08-10 08:26 UTC
#### deps:
ormlite-core,ormlite-jdbc  version:5.6
DB:postgresql 13.3-3

### code:
private String createUrl(String host, int port, String dbName, String userName, String userPasswd, boolean ssl) {
		return "jdbc:postgresql://" + host + ":" + port + "/" + dbName + "?user=" + userName + "&password=" + userPasswd
				+ "&ssl=" + ssl;
	}
	
connectionSource = new JdbcPooledConnectionSource(databaseUrl);
this.urlDAO = DaoManager.createDao(connectionSource, UrlData.class);
TableUtils.createTableIfNotExists(connectionSource, UrlData.class);//EXCEPTION

### trace:

![Screenshot_20210810_082558](https://user-images.githubusercontent.com/87483305/128834042-7e0db75a-90ef-4018-99b0-b6d9c64ae11d.png)

**Comment by JavLock** [comment] 2021-08-10 08:27
![Screenshot_20210810_082731](https://user-images.githubusercontent.com/87483305/128834285-9ceae9f0-4a41-44d0-a824-cd972ec3c262.png)

**Comment by JavLock** [comment] 2021-08-10 08:44
occurs when createTableIfNotExists is called when the table already exists.

**Comment by j256** [comment] 2021-08-16 23:10
Duplicate of #20

**Closed by j256** 2021-08-16 23:10 UTC
